# Scalar data types

Already seen

In [3]:
entero = 2
print type(entero)

string = 'asdfdasf'
print type(string)

flotante = 3.0
print type(flotante)

boolean = True
print type(boolean)

<type 'int'>
<type 'str'>
<type 'float'>
<type 'bool'>


# Data structures

Scaffolds in which we can put many instances of a data type.

## Lists 

Sequential, mutable data type

In [4]:
mi_primera_lista = [1,2,3,4]

In [5]:
lista_strings = ['a', 'b', 'c', 'd']

In [6]:
lista_anidada = [[1,2], [3,4]]
lista_anidada

[[1, 2], [3, 4]]

In [320]:
import pandas

# We can put anything inside a list, even a module!!

lista_heterogenea = ['a', 1, True, [], 1.0, int, pandas]

In [9]:
# A little trick I use to create lists of characters
lista_para_vagos = list('abcde')
print lista_para_vagos

['a', 'b', 'c', 'd', 'e']


### Indexing and slicing:


![slicing](http://infohost.nmt.edu/tcc/help/pubs/python25/web/fig/slicing.png)

In [11]:
lista_para_vagos[0]

'a'

In [12]:
lista_para_vagos[4]

'e'

In [13]:
lista_para_vagos[2]

'c'

In [14]:
lista_para_vagos[-3:]

['c', 'd', 'e']

In [16]:
lista_para_vagos[:-3]

['a', 'b']

In [17]:
lista_heterogenea

['a',
 1,
 True,
 [],
 1.0,
 int,
 <module 'pandas' from '/home/dani/dev/master-data-science/06_python_for_data_science/env/local/lib/python2.7/site-packages/pandas/__init__.pyc'>]

In [18]:
lista_heterogenea[-1] = 9
lista_heterogenea

['a', 1, True, [], 1.0, int, 9]

### Essential list methods

In [22]:
lista_heterogenea.insert(2, 'new')
lista_heterogenea

['a', 1, 'new', 'new', True, [], 1.0, int, 9]

In [25]:
retorno_de_insert = lista_heterogenea.insert(2, 'new')
print retorno_de_insert

None


\* None means *empty set* in Python. It represents the value returned by functions that do not return anything, among other things.

In [35]:
lista_heterogenea.insert(2, 'new')
lista_heterogenea

['a',
 1,
 'new',
 'new',
 'new',
 'new',
 'new',
 'new',
 'new',
 True,
 [],
 1.0,
 int,
 9]

In [31]:
a = 2 + 2
a

4

In [49]:
# When a function returns None or we derefence a variable
# containing None, The notebook doesn't print anything.
# .insert() returns None
retorno_de_insert

In [50]:
lista_heterogenea

['a',
 1,
 'new',
 'new',
 'new',
 'new',
 'new',
 'new',
 'new',
 True,
 [],
 1.0,
 int,
 9]

In [53]:
print lista_heterogenea
popped = lista_heterogenea.pop()
print popped
print lista_heterogenea

['a', 1, 'new', 'new', 'new', 'new', 'new', 'new', 'new', True, [], 1.0, <type 'int'>]
<type 'int'>
['a', 1, 'new', 'new', 'new', 'new', 'new', 'new', 'new', True, [], 1.0]


In [54]:
lista = lista_heterogenea

lista.append('appended')

In [55]:
lista

['a',
 1,
 'new',
 'new',
 'new',
 'new',
 'new',
 'new',
 'new',
 True,
 [],
 1.0,
 'appended']

In [56]:
# Both variables are pointing to the same list:

lista_heterogenea

['a',
 1,
 'new',
 'new',
 'new',
 'new',
 'new',
 'new',
 'new',
 True,
 [],
 1.0,
 'appended']

In [57]:
# To disconnect them, we'll have to copy all elements 
# from the original list. We can do that by doing a full slice:

lista = lista_heterogenea[:]

In [58]:
lista.append("x") == lista_heterogenea

False

In [64]:
# With .pop(), .insert() and .append() we can
# implement FIFO and LIFO queues:

cola = ['a','b','c']

def imprime_uno(cola):
    print cola.pop()
    
def aniade_uno_fifo(elem, cola):
    cola.insert(0, elem)

def aniade_uno_lifo(elem, cola):
    cola.append(elem)

print cola
imprime_uno(cola)
print cola
aniade_uno_fifo('x', cola)
print cola
aniade_uno_lifo('y', cola)
print cola
imprime_uno(cola)
print cola

['a', 'b', 'c']
c
['a', 'b']
['x', 'a', 'b']
['x', 'a', 'b', 'y']
y
['x', 'a', 'b']


In [65]:
cola

['x', 'a', 'b']

In [66]:
cola.index('a')

1

In [67]:
cola.sort()

In [68]:
cola

['a', 'b', 'x']

In [69]:
# Sorted vs sort: sorted returns a sorted copy 
# of the original list, while .sort() operates in place:
print lista
print sorted(lista)
print lista

['a', 1, 'new', 'new', 'new', 'new', 'new', 'new', 'new', True, [], 1.0, 'appended', 'x']
[1, True, 1.0, [], 'a', 'appended', 'new', 'new', 'new', 'new', 'new', 'new', 'new', 'x']
['a', 1, 'new', 'new', 'new', 'new', 'new', 'new', 'new', True, [], 1.0, 'appended', 'x']


In [70]:
# Ordering of heterogeneous values:

a = [pandas, 'x', True]

In [71]:
sorted(a)

[True,
 <module 'pandas' from '/home/dani/dev/master-data-science/06_python_for_data_science/env/local/lib/python2.7/site-packages/pandas/__init__.pyc'>,
 'x']

In [72]:
b = [pandas, True, 'x']

In [73]:
sorted(b)

[True,
 <module 'pandas' from '/home/dani/dev/master-data-science/06_python_for_data_science/env/local/lib/python2.7/site-packages/pandas/__init__.pyc'>,
 'x']

In [75]:
pandas < 'x'

True

In [76]:
True < pandas

True

In [77]:
c = b.sort()
print b
print c

[True, <module 'pandas' from '/home/dani/dev/master-data-science/06_python_for_data_science/env/local/lib/python2.7/site-packages/pandas/__init__.pyc'>, 'x']
None


In [78]:
for element in lista:
    print element

a
1
new
new
new
new
new
new
new
True
[]
1.0
appended
x


In [81]:
lista_para_vagos = list('abcde')

In [84]:
# Exercise: generate a list like lista_resultado 
# by iterating over lista_para_vagos:

lista_resultado = ['a1', 'b1', 'c1', 'd1', 'e1']

# Solution:
res = []
for element  in lista_para_vagos:
    res.append(element + '1')
    
res == lista_resultado

True

In [93]:
# Exercise: generate a list like nueva by iterating over
# lista_para_vagos. Enumerate() will be useful here:

nueva = ['a0', 'b1', 'c2', 'd3', 'e4']

res = []
for x in enumerate(lista_para_vagos):
    
    index = x[0]
    element = x[1]
    
    thing_to_append = element + str(index)
    res.append(thing_to_append)
    
res

['a0', 'b1', 'c2', 'd3', 'e4']

In [96]:
%time list('abcde')

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 11 µs


['a', 'b', 'c', 'd', 'e']

In [120]:
%%time 

# Let's see how long does it take to execute this:

nueva = ['a0', 'b1', 'c2', 'd3', 'e4']

res = []
for x in enumerate(lista_para_vagos):
    index = x[0]
    element = x[1]
    
    # Creamos el elemento que 
    thing_to_append = element + str(index)
    res.append(thing_to_append)
    
res

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 17.9 µs


In [122]:
# zip() is another very useful function for working with lists.

lista_para_vagos
nums = [0,1,2,3]

zip(lista_para_vagos, nums)

[('a', 0), ('b', 1), ('c', 2), ('d', 3)]

# Tuples

Ordered immutable sequences. They have all methods in lists that do not require mutation.

In [128]:
tupla = (tuple('xabcde'))

In [129]:
tupla

('x', 'a', 'b', 'c', 'd', 'e')

In [130]:
tupla[0] = 1

TypeError: 'tuple' object does not support item assignment

In [131]:
tupla[0]

'x'

In [132]:
sorted(tupla)

['a', 'b', 'c', 'd', 'e', 'x']

In [133]:
tupla

('x', 'a', 'b', 'c', 'd', 'e')

In [134]:
# We can transform lists in tuples:

tuple(lista_para_vagos)


('a', 'b', 'c', 'd', 'e')

In [135]:
# And unpack the values in the tuple into separate variables

a,b,c,d,e = lista_para_vagos

In [140]:
# That is very useful, for example, in for loops with enumerate.
# At each step, enumerate returns a tuple that we can unpack into
# index and element:

for index, letter in enumerate(lista_para_vagos):
    print letter + str(index)

a4
b4
c4
d4
e4


In [141]:
# Strings are another immutable sequence that we already saw:

string[0] = 's'

TypeError: 'str' object does not support item assignment

In [142]:
# Careful: tuples are immutable, but their contents may not be:

seq_confusa = (1, 'x', [])

In [143]:
seq_confusa[0] = 'n'

TypeError: 'tuple' object does not support item assignment

In [144]:
seq_confusa[2].append('oh my god!')

In [145]:
# The tuple has not changed: its third reference still points
# to the same list. It is that list that has changed:
seq_confusa

(1, 'x', ['oh my god!'])

# Dictionaries

Unordered, mutable, associative array. They connect pairs of elements.

In [148]:
capitales = {'Rusia' : 'Moscu', 'Espania' : 'Madrid'}

In [149]:
capitales

{'Espania': 'Madrid', 'Rusia': 'Moscu'}

In [150]:
# We can't access the items by position:

capitales[0]

KeyError: 0

In [151]:
capitales['Rusia']

'Moscu'

In [153]:
capitales.keys()

['Espania', 'Rusia']

In [154]:
capitales.values()

['Madrid', 'Moscu']

In [155]:
capitales.items()

[('Espania', 'Madrid'), ('Rusia', 'Moscu')]

In [156]:
# Mutable; we can reassign

capitales['Rusia'] = 'Leningrado'

In [157]:
capitales

{'Espania': 'Madrid', 'Rusia': 'Leningrado'}

In [321]:
# Keys can be any hashable type:

import numpy
opciones = {pandas : (1, 'max', int), numpy : (long, False)}

In [161]:
opciones[pandas]

(1, 'max', int)

In [162]:
opciones[numpy]

(long, False)

In [171]:
# We can iterate over keys:

for k in capitales.keys():
    print k

Espania
Rusia


In [172]:
# Or over both keys and items at the same time:

for k, v in capitales.items():
    print k
    print v

Espania
Madrid
Rusia
Leningrado


In [174]:
# The recommended way to do it is with iteritems(), 
# which provides an iterator over the k, v pairs:

for k,v in capitales.iteritems():
    print k
    print v    

Espania
Madrid
Rusia
Leningrado


In [175]:
capitales.items()

[('Espania', 'Madrid'), ('Rusia', 'Leningrado')]

In [176]:
capitales.iteritems()

<dictionary-itemiterator at 0x7f51c8708c58>

In [177]:
del(capitales['Rusia'])

In [178]:
capitales

{'Espania': 'Madrid'}

In [181]:
capitales.pop('Espania')

'Madrid'

# Numpy

Linear algebra library. It extends Python with convenient and fast matrix and vector operations, a bit like Matlab.

In [182]:
import numpy as np

In [184]:
# The array is the base.

np.array([12,24,53,546])

array([ 12,  24,  53, 546])

In [185]:
mi_array = np.array([12,24,53,546])

In [186]:
# Arrays are typed

mi_array.dtype

dtype('int64')

In [189]:
# These two operations are strictly equivalent. 
# Numpy is waaay faster:

%time x = np.arange(100000) + 1

%time x = map(lambda x: x + 1, xrange(100000))

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 746 µs
CPU times: user 12 ms, sys: 8 ms, total: 20 ms
Wall time: 17.3 ms


### Matrix operations

In [191]:
mi_array.shape

(4,)

In [196]:
mi_matriz = np.arange(12).reshape(3,4)
mi_matriz

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [197]:
otra = mi_matriz.reshape(4,3)
mi_matriz

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [198]:
otra

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [199]:
mi_matriz.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [200]:
# Remember: matrix multiplication has requirements about the shape of the matrices

mi_matriz.dot(mi_matriz)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [202]:
producto = mi_matriz.dot(mi_matriz.transpose())
producto

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

### Accessing elements

In [204]:
producto[2,2]

366

In [205]:
producto[2]

array([ 62, 214, 366])

In [206]:
producto[2][2]

366

In [207]:
# Slicing

producto[1:]

array([[ 38, 126, 214],
       [ 62, 214, 366]])

In [208]:
# The doct product of two vectors is a scalar

producto[0].dot(producto[1])

18588

In [209]:
producto

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [210]:
producto * 2

array([[ 28,  76, 124],
       [ 76, 252, 428],
       [124, 428, 732]])

In [212]:
# Selecting columns

producto[:][1]

array([ 38, 126, 214])

In [214]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [217]:
producto[2] = producto[2] - 50
producto

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [-38, 114, 266]])

In [219]:
# There are a ton of linear algebra tools in numpy.linalg:

import numpy.linalg as la

help(la)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

FILE
    /home/dani/dev/master-data-science/06_python_for_data_science/env/local/lib/python2.7/site-packages/numpy/linalg/__init__.py

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        E

In [224]:
producto[2][0] = 0
producto

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [  0, 114,   0]])

In [225]:
la.inv(producto)

array([[ 0.334375  , -0.096875  , -0.00438596],
       [ 0.        ,  0.        ,  0.00877193],
       [-0.059375  ,  0.021875  , -0.00438596]])

In [226]:
# Multiplying a matrix by its inverse returns the identity matrix:

producto.dot(la.inv(producto))

array([[  1.00000000e+00,   0.00000000e+00,   5.55111512e-17],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])

### Exercise:

A mother's and her child's ages sum 30 years. In 15 years, she will be twice is age. Find out both ages.

Solve the linear equation system like this:

$ A \cdot X = B $

$ A^{-1} \cdot A \cdot X = A^{-1} \cdot B $

$ X = A^{-1} \cdot B $

In [227]:
A = np.array([[1,1],[2,-1]])
A

array([[ 1,  1],
       [ 2, -1]])

In [230]:
B = np.array([30,-15])
B

array([ 30, -15])

In [231]:
np.linalg.inv(A).dot(B)

array([  5.,  25.])

### Exercise:

In farm where they grow chickens and rabbits, there are 35 heads and 94 legs. How many chickens and rabbits are there?

Solve the linear equation system like this:

$ A \cdot X = B $

$ A^{-1} \cdot A \cdot X = A^{-1} \cdot B $

$ X = A^{-1} \cdot B $

In [234]:
A = np.array([[1,1], [4,2]])
B = np.array([35,94])

np.linalg.inv(A).dot(B)

array([ 12.,  23.])

In [235]:
12 * 4 + 23 * 2

94

### Indexing arrays using boolean arrays as masks:

In [236]:
np.matrix

numpy.matrixlib.defmatrix.matrix

In [242]:
producto

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [  0, 114,   0]])

In [240]:
producto < 20

array([[ True, False, False],
       [False, False, False],
       [ True, False,  True]], dtype=bool)

In [241]:
producto[producto < 20]

array([14,  0,  0])

In [246]:
np.where(producto < 20)

(array([0, 2, 2]), array([0, 0, 2]))

# Pandas

Library for analysis of tabular data. Extends numpy for the specific use case of two dimensional tables that might have non-numeric data. 

In [257]:
import pandas as pd

### pd.Series

pandas's core abstraction. You can think of it as a combination of a numpy array and a dictionary.


In [260]:
pd.Series([1,2,3,4], index=list('abcd'))

a    1
b    2
c    3
d    4
dtype: int64

In [261]:
poblacion = pd.Series([1.5e06,3e06,5e05], index = ['Barcelona', 'Madrid', 'Zaragoza'])

In [263]:
poblacion['Madrid']

3000000.0

In [264]:
poblacion > 2e06

Barcelona    False
Madrid        True
Zaragoza     False
dtype: bool

In [268]:
# miniexercise: Extract the population of the city or 
# cities that have more than 2000000 inhabitants.

res = poblacion[poblacion > 2e06]

print res
print type(res)

Madrid    3000000.0
dtype: float64
<class 'pandas.core.series.Series'>


In [272]:
equiv = pd.Series({'Madrid': 3e6, 'Barcelona' : 1.5e6, 'Zaragoza': 5e5})

In [273]:
equiv == poblacion

Barcelona    True
Madrid       True
Zaragoza     True
dtype: bool

In [274]:
superficie = pd.Series({'Madrid': 600, 'Barcelona' : 200, 'Zaragoza': 50})

In [276]:
# If two Series share the index, we can do operations on them:

densidad = poblacion / superficie

In [277]:
densidad

Barcelona     7500.0
Madrid        5000.0
Zaragoza     10000.0
dtype: float64

In [278]:
# We can use one to mask the other:

densidad[poblacion > 1e6]

Barcelona    7500.0
Madrid       5000.0
dtype: float64

## Dataframe

The object we will be using the most when working with pandas.

In [284]:
paises = pd.DataFrame({'Poblacion' : [1e7, 4e7, 6e7], 'Idioma' : ['Portugues', 'Espaniol', 'Frances']})

In [285]:
paises

Idioma   Poblacion
0  Portugues  10000000.0
1   Espaniol  40000000.0
2    Frances  60000000.0

In [286]:
paises.columns

Index([u'Idioma', u'Poblacion'], dtype='object')

In [287]:
# Dataframes have indexes, which are much more useful when meaningful 
# than when they are automatically created by pandas:
paises.index

RangeIndex(start=0, stop=3, step=1)

In [291]:
paises_bien = pd.DataFrame(
    {'Poblacion' : [1e7, 4e7, 6e7], 'Idioma' : ['Portugues', 'Espaniol', 'Frances']},
    index=['Portugal', 'Espania', 'Italia'])

In [292]:
paises_bien

Idioma   Poblacion
Portugal  Portugues  10000000.0
Espania    Espaniol  40000000.0
Italia      Frances  60000000.0

In [295]:
# When we access like this, we are retrieving columns, not rows:

paises_bien['Espania']

KeyError: 'Espania'

In [296]:
paises_bien['Idioma']

Portugal    Portugues
Espania      Espaniol
Italia        Frances
Name: Idioma, dtype: object

In [297]:
# We can also access columns like this, but then kittens die:

paises_bien.Idioma

Portugal    Portugues
Espania      Espaniol
Italia        Frances
Name: Idioma, dtype: object

In [298]:
paises_bien['1970'] = ['Dictadura', 'Dictadura','Democracia']

In [300]:
paises_bien

Idioma   Poblacion        1970
Portugal  Portugues  10000000.0   Dictadura
Espania    Espaniol  40000000.0   Dictadura
Italia      Frances  60000000.0  Democracia

In [301]:
paises_bien['1970']

Portugal     Dictadura
Espania      Dictadura
Italia      Democracia
Name: 1970, dtype: object

In [302]:
paises_bien.1970

SyntaxError: invalid syntax (<ipython-input-302-d2bc15a52503>, line 1)

In [305]:
paises_bien['1970']['Portugal']

'Dictadura'

In [306]:
# If we need to extract rows, we can either extract 
# them with the .ix attribute, or by position

paises_bien.ix['Portugal']

Idioma       Portugues
Poblacion        1e+07
1970         Dictadura
Name: Portugal, dtype: object

In [307]:
paises_bien[:2]

Idioma   Poblacion       1970
Portugal  Portugues  10000000.0  Dictadura
Espania    Espaniol  40000000.0  Dictadura

In [310]:
# Careful! this asks for the row with index value = 1, which doesn't exist.

paises_bien[1]

KeyError: 1

In [318]:
paises_bien

Idioma   Poblacion        1970
Portugal  Portugues  10000000.0   Dictadura
Espania    Espaniol  40000000.0   Dictadura
Italia      Frances  60000000.0  Democracia

In [319]:
# IF we want the second row, we need to use the .iloc attribute:
paises_bien.iloc[1]

Idioma        Espaniol
Poblacion        4e+07
1970         Dictadura
Name: Espania, dtype: object